import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Sidebar from "../components/Sidebar";
import HomePage from "../components/Profile";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";
import Widgets from "../components/Widgets";

const Home: NextPage = () => {
  const [Component, setComponent] = useState(HomePage);
  const { isAuthenticated } = useMoralis();
  if (!isAuthenticated) {
    return <Login />;
  }
  return (
    <div className="bg-gray-900 h-screen p-5">
      <Head>
        <title>Twitter Dapp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/6.jpg" />
      </Head>

      <main className="flex max-w-7xl mx-auto space-x-10 p-5 h-full">
        <Sidebar setComponent={setComponent} />
        <div className="flex flex-1 h-full border-x-2 border-gray-800 p-2 overflow-y-scroll scroll-smooth scrollbar-hide">
          {Component}
        </div>
        <Widgets />
      </main>
    </div>
  );
};

export default Home;
